name: Test Python Installer Script

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run installation script
      run: |
        sudo bash scripts/install_pyenv.sh
