name: Test Python Installer Script

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run installation script
      run: |
        # Run the script directly from the repo
        bash scripts/install_pyenv.sh

    - name: Verify Python installation
      run: |
        python --version
        pip --version
